// Code generated by scripts/gen_cli.go; DO NOT EDIT.
package main

import (
	"github.com/nskaggs/perfuncted"
	"github.com/spf13/cobra"
)

func autogenScreenCommands(openPF func() (*perfuncted.Perfuncted, error)) []*cobra.Command {
	cmds := []*cobra.Command{}
	return cmds
}
func autogenInputCommands(openPF func() (*perfuncted.Perfuncted, error)) []*cobra.Command {
	cmds := []*cobra.Command{}
	return cmds
}
func autogenWindowCommands(openPF func() (*perfuncted.Perfuncted, error)) []*cobra.Command {
	cmds := []*cobra.Command{}
	return cmds
}
func autogenClipboardCommands(openPF func() (*perfuncted.Perfuncted, error)) []*cobra.Command {
	cmds := []*cobra.Command{}
	return cmds
}
