// Code generated by scripts/gen_cli.go; DO NOT EDIT.
package main

import (
	"fmt"
	"github.com/spf13/cobra"
)

func autogenScreenCommands(openPF sessionOpener) []*cobra.Command {
	cmds := []*cobra.Command{}

	// grab-full-hash: wrapper for perfuncted.GrabFullHash

	cmd_screen_grab_full_hash := &cobra.Command{
		Use:   "grab-full-hash",
		Short: "Print the CRC32 hash of the full screen contents",
		Long:  "Captures the full screen and prints the CRC32 pixel hash as a zero-padded\nhex integer. Useful as a quick change-detection probe without saving any files.",
		RunE: func(cmd *cobra.Command, args []string) error {
			pf, err := openPF(cmd.Context())
			if err != nil {
				return err
			}
			defer pf.Close()
			h, err := pf.Screen.GrabFullHash(cmd.Context())
			if err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "%08x\n", h)
			return nil
		},
	}

	cmds = append(cmds, cmd_screen_grab_full_hash)

	// wait-for-no-change: wrapper for perfuncted.WaitForNoChange
	var cmd_screen_wait_for_no_change_rect string
	var cmd_screen_wait_for_no_change_stable int
	var cmd_screen_wait_for_no_change_poll string
	cmd_screen_wait_for_no_change := &cobra.Command{
		Use:   "wait-for-no-change",
		Short: "Wait for a screen region to stop changing",
		RunE: func(cmd *cobra.Command, args []string) error {
			pf, err := openPF(cmd.Context())
			if err != nil {
				return err
			}
			defer pf.Close()
			r_0, err := parseRect(cmd_screen_wait_for_no_change_rect)
			if err != nil {
				return err
			}
			// flag cmd_screen_wait_for_no_change_stable (int) already parsed into var
			cmd_screen_wait_for_no_change_poll_dur, err := parseDuration(cmd_screen_wait_for_no_change_poll, 0)
			if err != nil {
				return err
			}
			h, err := pf.Screen.WaitForNoChange(cmd.Context(), r_0, cmd_screen_wait_for_no_change_stable, cmd_screen_wait_for_no_change_poll_dur)
			if err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "%08x\n", h)
			return nil
		},
	}
	cmd_screen_wait_for_no_change.Flags().StringVar(&cmd_screen_wait_for_no_change_rect, "rect", "0,0,1920,1080", "region to monitor as x0,y0,x1,y1")
	cmd_screen_wait_for_no_change.Flags().IntVar(&cmd_screen_wait_for_no_change_stable, "stable", 0, "number of stable samples required")
	cmd_screen_wait_for_no_change.Flags().StringVar(&cmd_screen_wait_for_no_change_poll, "poll", "", "polling interval (e.g. 200ms)")

	cmds = append(cmds, cmd_screen_wait_for_no_change)

	// wait-for-no-change-from: wrapper for perfuncted.WaitForNoChangeFrom
	var cmd_screen_wait_for_no_change_from_rect string
	var cmd_screen_wait_for_no_change_from_initial string
	var cmd_screen_wait_for_no_change_from_stable int
	var cmd_screen_wait_for_no_change_from_poll string
	cmd_screen_wait_for_no_change_from := &cobra.Command{
		Use:   "wait-for-no-change-from",
		Short: "Wait for a screen region to stop changing, starting from an initial hash",
		RunE: func(cmd *cobra.Command, args []string) error {
			pf, err := openPF(cmd.Context())
			if err != nil {
				return err
			}
			defer pf.Close()
			r_0, err := parseRect(cmd_screen_wait_for_no_change_from_rect)
			if err != nil {
				return err
			}
			cmd_screen_wait_for_no_change_from_initial_parsed, err := parseHash(cmd_screen_wait_for_no_change_from_initial)
			if err != nil {
				return err
			}
			// flag cmd_screen_wait_for_no_change_from_stable (int) already parsed into var
			cmd_screen_wait_for_no_change_from_poll_dur, err := parseDuration(cmd_screen_wait_for_no_change_from_poll, 0)
			if err != nil {
				return err
			}
			h, err := pf.Screen.WaitForNoChangeFrom(cmd.Context(), r_0, cmd_screen_wait_for_no_change_from_initial_parsed, cmd_screen_wait_for_no_change_from_stable, cmd_screen_wait_for_no_change_from_poll_dur)
			if err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "%08x\n", h)
			return nil
		},
	}
	cmd_screen_wait_for_no_change_from.Flags().StringVar(&cmd_screen_wait_for_no_change_from_rect, "rect", "0,0,1920,1080", "region to monitor as x0,y0,x1,y1")
	cmd_screen_wait_for_no_change_from.Flags().StringVar(&cmd_screen_wait_for_no_change_from_initial, "initial", "", "initial CRC32 hash (decimal or 0xhex)")
	cmd_screen_wait_for_no_change_from.Flags().IntVar(&cmd_screen_wait_for_no_change_from_stable, "stable", 0, "number of stable samples required")
	cmd_screen_wait_for_no_change_from.Flags().StringVar(&cmd_screen_wait_for_no_change_from_poll, "poll", "", "polling interval (e.g. 200ms)")

	cmds = append(cmds, cmd_screen_wait_for_no_change_from)
	return cmds
}
