name: golangci-lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.26.0

      - name: Run golangci-lint
        continue-on-error: true
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.11.4
          args: --timeout=5m
